### PR TITLE
feat: allow to override HMAC validation

### PR DESCRIPTION
**Pull request by schiller-manuel**
since auth guards cannot be overriden (see https://github.com/nestjs/nest/issues/8011#issuecomment-926544072), I moved the logic from HMAC guard into a service that can be overridden.

see #360

@tolgap  please review, especially:
- is this the best way to implement this feature?
- is this a breaking change, since users of the `@ShopifyHmac` decorator now need to import the `ShopifyHmac` module? (or maybe they don't and this was just necessary for the webhook module?)

### CODE REVIEW

**Comment by tolgap** [comment]
Hey @schiller-manuel , do you know what use case necessitates this change? 🙂

**Comment by ashleyww93** [comment]
@tolgap @schiller-manuel Thank you for this.

I totally missed this PR, and have now opened my own that does this in a different way, that includes no breaking changes.

I took inspiration from the sessionService implementation and made it accept an optional function which is called to get the shared secret.

This function is provided with the shop domain, so you can pull the shared secret from anywhere(in my case our database), and then return it. If you don't have one, or the domain is unknown to you... return undefined.

**Comment by schiller-manuel** [comment]
@tolgap what do we do about this? merge? close?

**Comment by tolgap** [comment]
@schiller-manuel Thank you for your work on this again!

But seeing as the original issuer was attempting to use private apps, which is unsupported in `@shopify/shopify-api`, I don't feel that should be part of this package. I would suggest closing these PRs.

I proposed a workaround for @ashleyww93 using an `ExceptionFilter`.

**Pull request closed without merging**
