### PR TITLE
feat: support shared secret in webhooks

### PR DESCRIPTION
**Pull request by ashleyww93**
Resolves: https://github.com/nestjs-shopify/nestjs-shopify/issues/360#issue-2092578144

Without any breaking changes, you can simply provide a function in the factory core ShopifyCoreModule like so.

```
ShopifyCoreModule.forRootAsync({
            imports: [ConfigModule, SessionModule, RetailerModule],
            inject: [
                ConfigService<typeof shopifySchema>,
                ConfigService<typeof runtimeSchema>,
                DatabaseSessionStorage,
                RetailerService,
            ],
            useFactory: async (
                shopifyConfigService: ConfigService<typeof shopifySchema>,
                runtimeConfigService: ConfigService<typeof runtimeSchema>,
                sessionStorage: DatabaseSessionStorage,
                retailerService: RetailerService,
            ) => {
                return {
                    getSharedSecret: retailerService.getSharedSecret,
                    sessionStorage: sessionStorage,
                    apiKey: shopifyConfigService.get<string>('SHOPIFY_API_KEY')!,
                    apiSecretKey: shopifyConfigService.get<string>('SHOPIFY_API_SECRET_KEY')!,
                    apiVersion: ApiVersion.January24,
                    hostName: runtimeConfigService.get('HOST')!.replace(/https:\/\//, ''),
                    isEmbeddedApp: true,
                    scopes: ['scopes'],
                };
            },
        });
````

### CODE REVIEW

**Comment by schiller-manuel** [comment]
can you please point me to relevant Shopify documentation pages about that "shared secret"?

**Comment by ashleyww93** [comment]
I can’t find it right now, but they came from private apps (each retailer had a private app that connected to our API). During install (this did not happen via OAuth) they would provide their access token and the shared secret. 

I think these are now called Custom Apps and each app has their own API Secret. 

If we were only supporting one custom app (and no public app), we could just use the secret in the environment, but as we have a production app, and some long running retailers refusing to upgrade we have to be able to be able to accept webhooks from these old private apps. 

IMG_5614

https://help.shopify.com/en/manual/apps/app-types/custom-apps

This is only useful for apps that were originally only intended for one retailer and then decided to release on the Shopify App Store. 

I can continue using my patch if you don’t want this functionality built in, but as this was recommended to us by Shopify it would be useful to have it without needing a patch.

**Comment by schiller-manuel** [comment]
thanks for the explanation. If this library shall support any of this I would prefer my PR #361 so you have a way to hook in your custom logic but we don't have to maintain this logic in the library.
@tolgap what's your take on this?

**Comment by ashleyww93** [comment]
@schiller-manuel I understand, but to explain there is no logic to maintain other than if webhook validation fails for the built in secret, then the library calls a function that supplies the shop specific secret and then tries again with that secret. 

That is the only change required, which I why I made it an optional function, which if not supplied the original logic remains largely unchanged. 

They both achieve the same goal, so I’m not overly precious about which is merged; but given there is no other reason to change how the hmac validation works, i thought it was best to simply provide a function that can provide the secret.

**Pull request closed without merging**
